# SELECT ROUND(AVG(IF(LENGTH>10, LENGTH, 10)), 2) AS AVERAGE_LENGTH
# FROM FISH_INFO

SELECT ROUND(AVG(CASE WHEN LENGTH IS NULL THEN 10
                       WHEN LENGTH > 10 THEN LENGTH
                       END),2) AS AVERAGE_LENGTH
FROM FISH_INFO