# 1. 음식종류별로 즐겨찾기수가 가장 많은 식당 찾기
# SELECT MAX(FAVORITES)
# FROM REST_INFO
# GROUP BY FOOD_TYPE

# 2. 1을 서브쿼리로 WHERE 절에 삽입
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO
WHERE FAVORITES IN (SELECT MAX(FAVORITES)
                    FROM REST_INFO
                    GROUP BY FOOD_TYPE)
GROUP BY FOOD_TYPE
ORDER BY FOOD_TYPE DESC