WITH DESC_ID AS (
    SELECT ID,  PERCENT_RANK() over (order by SIZE_OF_COLONY DESC) as RANKING
    FROM ECOLI_DATA
)
SELECT ID, CASE WHEN RANKING <= 0.25 THEN "CRITICAL"
                WHEN RANKING <= 0.5 THEN "HIGH"
                WHEN RANKING <= 0.75 THEN "MEDIUM"
            ELSE "LOW" END AS COLONY_NAME
FROM DESC_ID
ORDER BY ID