# 자동차 종류 : 트럭
# 대여 기록 별 대여 금액(FEE)
# 대여 기록 ID, 대여 금액 리스트
# 대여 금액 내림차순, 대여 기록 ID 내림차순

SELECT H.HISTORY_ID AS HISTORY_ID, CASE WHEN DATEDIFF(END_DATE, START_DATE)+1 >= 90 THEN ROUND(DAILY_FEE*(100-(SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE DURATION_TYPE LIKE '90%' AND CAR_TYPE='트럭'))*(DATEDIFF(END_DATE, START_DATE)+1)/100)
                    WHEN DATEDIFF(END_DATE, START_DATE)+1 >= 30 THEN ROUND(DAILY_FEE*(100-(SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE DURATION_TYPE LIKE '30%' AND CAR_TYPE='트럭'))*(DATEDIFF(END_DATE, START_DATE)+1)/100)
                    WHEN DATEDIFF(END_DATE, START_DATE)+1 >= 7 THEN ROUND(DAILY_FEE*(100-(SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE DURATION_TYPE LIKE '7%' AND CAR_TYPE='트럭'))*(DATEDIFF(END_DATE, START_DATE)+1)/100)
                    ELSE ROUND(DAILY_FEE*(DATEDIFF(END_DATE, START_DATE)+1))
                    END AS FEE
FROM CAR_RENTAL_COMPANY_CAR C JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON C.CAR_ID = H.CAR_ID JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON C.CAR_TYPE = P.CAR_TYPE
WHERE C.CAR_TYPE = '트럭'
GROUP BY H.HISTORY_ID
ORDER BY FEE DESC, HISTORY_ID DESC