SELECT F.FLAVOR
FROM FIRST_HALF AS F JOIN JULY AS J ON F.SHIPMENT_ID = J.SHIPMENT_ID
ORDER BY F.TOTAL_ORDER+(SELECT SUM(TOTAL_ORDER)
                        FROM JULY J
                        WHERE F.FLAVOR = J.FLAVOR
                        GROUP BY FLAVOR) DESC
LIMIT 3