-- CONV(데이터, 원본 진법, 변환할 진법)
-- 비트 연산자
SELECT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM DEVELOPERS D
WHERE (
    SELECT SUM(S.CODE)
    FROM SKILLCODES S
    WHERE S.CATEGORY = 'Front End'
) & D.SKILL_CODE > 0
ORDER BY D.ID;
