# ID 1 : 0001 -> 보유형질 1
# ID 4 : 0010 -> 보유형질 2

# SELECT DISTINCT C.ID, C.GENOTYPE, P.GENOTYPE AS PARENT_GENOTYPE
# FROM ECOLI_DATA C, ECOLI_DATA P
# WHERE C.GENOTYPE & P.GENOTYPE = P.GENOTYPE AND C.ID = P.PARENT_ID
# ORDER BY C.ID

SELECT C.ID, C.GENOTYPE, P.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA C, ECOLI_DATA P
WHERE C.GENOTYPE & P.GENOTYPE = P.GENOTYPE AND C.PARENT_ID = P.ID
ORDER BY C.ID