# 분화된 연도별 가장 큰 대장균의 크기 - 각 대장균의 크기
# GROUP BY에서 YEAR(DIFFERENTIATION_DATE)를 기준으로 그룹화했지만, SELECT 절의 나머지 열(SIZE_OF_COLONY, ID)이 집계 함수로 처리되지 않았고 GROUP BY 절에도 포함되지 않았습니다.
# SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) - SIZE_OF_COLONY AS YEAR_DEV, ID
# FROM ECOLI_DATA
# GROUP BY YEAR(DIFFERENTIATION_DATE)
# ORDER BY YEAR, YEAR_DEV

# WITH MAX_YEAR AS (
#     SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_Y
#     FROM ECOLI_DATA
#     GROUP BY YEAR(DIFFERENTIATION_DATE)
# )

# SELECT YEAR(E.DIFFERENTIATION_DATE) AS YEAR, M.MAX_Y - E.SIZE_OF_COLONY AS YEAR_DEV, E.ID
# FROM ECOLI_DATA E JOIN MAX_YEAR M ON YEAR(E.DIFFERENTIATION_DATE) = M.YEAR
# GROUP BY YEAR(E.DIFFERENTIATION_DATE)
# ORDER BY YEAR, YEAR_DEV

WITH MAX_YEAR AS (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_Y
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
)

SELECT YEAR(E.DIFFERENTIATION_DATE) AS YEAR, M.MAX_Y - E.SIZE_OF_COLONY AS YEAR_DEV, E.ID
FROM ECOLI_DATA E JOIN MAX_YEAR M ON YEAR(E.DIFFERENTIATION_DATE) = M.YEAR
ORDER BY YEAR, YEAR_DEV