SELECT ID, FISH_NAME, LENGTH
FROM FISH_INFO FI JOIN FISH_NAME_INFO FNI ON FI.FISH_TYPE = FNI.FISH_TYPE
WHERE LENGTH IN (SELECT MAX(LENGTH) AS LENGTH
                 FROM FISH_INFO FI
                 WHERE FI.FISH_TYPE = FNI.FISH_TYPE)
ORDER BY ID