## 조회수가 가장 높은 중고거래 게시물
# SELECT BOARD_ID
# FROM USED_GOODS_BOARD AS B
# ORDER BY VIEWS
# LIMIT 1

# This version of MySQL doesn't yet support 'LIMIT & IN/ALL/ANY/SOME subquery'
SELECT CONCAT("/home/grep/src/", F.BOARD_ID, "/", F.FILE_ID, F.FILE_NAME, F.FILE_EXT) AS FILE_PATH
FROM USED_GOODS_BOARD AS B JOIN USED_GOODS_FILE AS F ON B.BOARD_ID = F.BOARD_ID
WHERE VIEWS IN (SELECT MAX(VIEWS)
                FROM USED_GOODS_BOARD AS B)
ORDER BY F.FILE_ID DESC