SELECT CASE WHEN (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY = 'Front End') & SKILL_CODE and (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python') & SKILL_CODE THEN 'A'
            WHEN (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#') & SKILL_CODE THEN 'B'
            WHEN (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY = 'Front End') & SKILL_CODE THEN 'C' ELSE '' END AS GRADE, ID, EMAIL
FROM DEVELOPERS
HAVING GRADE != ''
ORDER BY GRADE, ID